# Phase 1: Data Understanding

This notebook explores the six source CSV files. It displays the findings inside the notebook and does not create a separate report.

## 1. Import the required libraries

In [1]:
from pathlib import Path
import pandas as pd

## 2. Set the data folder path

The code works when the notebook is opened from either the project folder or the `notebooks` folder.

In [2]:
current_folder = Path.cwd()

if current_folder.name == 'notebooks':
    project_folder = current_folder.parent
else:
    project_folder = current_folder

data_folder = project_folder / 'data' / 'raw'
print('Data folder:', data_folder)

Data folder: d:\Desktop\Pune Internship\Global-Electronics-Retail-Sales-Analysis-and-Business-Intelligence-Dashboard\data\raw

## 3. Load the CSV files

`Customers.csv` uses Windows-1252 encoding. The remaining files use UTF-8.

In [3]:
customers = pd.read_csv(data_folder / 'Customers.csv', encoding='cp1252', keep_default_na=False, na_values=[''])
products = pd.read_csv(data_folder / 'Products.csv', keep_default_na=False, na_values=[''])
sales = pd.read_csv(data_folder / 'Sales.csv', keep_default_na=False, na_values=[''])
stores = pd.read_csv(data_folder / 'Stores.csv', keep_default_na=False, na_values=[''])
exchange_rates = pd.read_csv(data_folder / 'Exchange_Rates.csv', keep_default_na=False, na_values=[''])
data_dictionary = pd.read_csv(data_folder / 'Data_Dictionary.csv', keep_default_na=False, na_values=[''])

print('All CSV files loaded successfully.')

All CSV files loaded successfully.

## 4. Preview the datasets

In [4]:
display(sales.head())
display(customers.head())
display(products.head())
display(stores.head())
display(exchange_rates.head())

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

   StoreKey    Country                         State  Square Meters  Open Date
0         1  Australia  Australian Capital Territory          595.0   1/1/2008
1         2  Australia            Northern Territory          665.0  1/12/2008
2         3  Australia               South Australia         2000.0   1/7/2012
3         4  Australia                      Tasmania         2000.0   1/1/2010
4         5  Australia                      Victoria         2000.0  12/9/2015

       Date Currency  Exchange
0  1/1/2015      USD    1.0000
1  1/1/2015      CAD    1.1583
2  1/1/2015      AUD    1.2214
3  1/1/2015      EUR    0.8237
4  1/1/2015      GBP    0.6415

## 5. Count rows and columns

A dictionary keeps each table name together with its DataFrame. This makes it easy to repeat the same check for every dataset.

In [5]:
datasets = {
    'Customers': customers,
    'Products': products,
    'Sales': sales,
    'Stores': stores,
    'Exchange Rates': exchange_rates,
    'Data Dictionary': data_dictionary,
}

dataset_sizes = []

for dataset_name, dataframe in datasets.items():
    dataset_sizes.append({
        'Dataset': dataset_name,
        'Rows': dataframe.shape[0],
        'Columns': dataframe.shape[1],
    })

dataset_sizes = pd.DataFrame(dataset_sizes)
display(dataset_sizes)

           Dataset   Rows  Columns
0        Customers  15266       10
1         Products   2517       10
2            Sales  62884        9
3           Stores     67        5
4   Exchange Rates  11215        3
5  Data Dictionary     37        3

## 6. Check column names and data types

In [6]:
for dataset_name, dataframe in datasets.items():
    print(f'\n{dataset_name}')
    print(dataframe.dtypes)

Customers
CustomerKey     int64
Gender         object
Name           object
City           object
State Code     object
State          object
Zip Code       object
Country        object
Continent      object
Birthday       object
dtype: object

Products
ProductKey         int64
Product Name      object
Brand             object
Color             object
Unit Cost USD     object
Unit Price USD    object
SubcategoryKey     int64
Subcategory       object
CategoryKey        int64
Category          object
dtype: object

Sales
Order Number      int64
Line Item         int64
Order Date       object
Delivery Date    object
CustomerKey       int64
StoreKey          int64
ProductKey        int64
Quantity          int64
Currency Code    object
dtype: object

Stores
StoreKey           int64
Country           object
State             object
Square Meters    float64
Open Date         object
dtype: object

Exchange Rates
Date         object
Currency     object
Exchange    float64
dtype: object

Data Dictionary
Table          object
Field          object
Description    object
dtype: object

## 7. Check missing values

In [7]:
missing_value_results = []

for dataset_name, dataframe in datasets.items():
    for column_name in dataframe.columns:
        missing_count = dataframe[column_name].isna().sum()
        missing_percent = (missing_count / len(dataframe)) * 100

        if missing_count > 0:
            missing_value_results.append({
                'Dataset': dataset_name,
                'Column': column_name,
                'Missing Values': missing_count,
                'Missing Percentage': round(missing_percent, 2),
            })

missing_values = pd.DataFrame(missing_value_results)
display(missing_values)

  Dataset         Column  Missing Values  Missing Percentage
0   Sales  Delivery Date           49719               79.06
1  Stores  Square Meters               1                1.49

## 8. Check complete duplicate rows

In [8]:
for dataset_name, dataframe in datasets.items():
    duplicate_count = dataframe.duplicated().sum()
    print(f'{dataset_name}: {duplicate_count} duplicate rows')

Customers: 0 duplicate rows
Products: 0 duplicate rows
Sales: 0 duplicate rows
Stores: 0 duplicate rows
Exchange Rates: 0 duplicate rows
Data Dictionary: 0 duplicate rows

## 9. Check primary keys

Sales uses a combined key because one order can contain several line items.

In [9]:
customer_key_duplicates = customers.duplicated(subset=['CustomerKey']).sum()
product_key_duplicates = products.duplicated(subset=['ProductKey']).sum()
store_key_duplicates = stores.duplicated(subset=['StoreKey']).sum()
sales_key_duplicates = sales.duplicated(subset=['Order Number', 'Line Item']).sum()
rate_key_duplicates = exchange_rates.duplicated(subset=['Date', 'Currency']).sum()

print('Duplicate customer keys:', customer_key_duplicates)
print('Duplicate product keys:', product_key_duplicates)
print('Duplicate store keys:', store_key_duplicates)
print('Duplicate sales keys:', sales_key_duplicates)
print('Duplicate exchange-rate keys:', rate_key_duplicates)

Duplicate customer keys: 0
Duplicate product keys: 0
Duplicate store keys: 0
Duplicate sales keys: 0
Duplicate exchange-rate keys: 0

## 10. Convert date columns

In [10]:
sales['Order Date'] = pd.to_datetime(sales['Order Date'], errors='coerce')
sales['Delivery Date'] = pd.to_datetime(sales['Delivery Date'], errors='coerce')
customers['Birthday'] = pd.to_datetime(customers['Birthday'], errors='coerce')
stores['Open Date'] = pd.to_datetime(stores['Open Date'], errors='coerce')
exchange_rates['Date'] = pd.to_datetime(exchange_rates['Date'], errors='coerce')

print('Date columns converted.')

Date columns converted.

## 11. Find the sales date range and transaction counts

In [11]:
first_order_date = sales['Order Date'].min()
last_order_date = sales['Order Date'].max()
sales_line_count = len(sales)
order_count = sales['Order Number'].nunique()

print('First order date:', first_order_date.date())
print('Last order date:', last_order_date.date())
print('Sales lines:', sales_line_count)
print('Distinct orders:', order_count)

First order date: 2016-01-01
Last order date: 2021-02-20
Sales lines: 62884
Distinct orders: 26326

## 12. Check relationships between tables

In [12]:
missing_customer_keys = (~sales['CustomerKey'].isin(customers['CustomerKey'])).sum()
missing_product_keys = (~sales['ProductKey'].isin(products['ProductKey'])).sum()

physical_store_sales = sales[sales['StoreKey'] != 0]
missing_store_keys = (~physical_store_sales['StoreKey'].isin(stores['StoreKey'])).sum()
online_sales_lines = (sales['StoreKey'] == 0).sum()

print('Sales with missing customer:', missing_customer_keys)
print('Sales with missing product:', missing_product_keys)
print('Sales with missing physical store:', missing_store_keys)
print('Sales using StoreKey 0:', online_sales_lines)

Sales with missing customer: 0
Sales with missing product: 0
Sales with missing physical store: 0
Sales using StoreKey 0: 13165

## 13. Check exchange-rate coverage

In [13]:
sales_with_rates = sales.merge(
    exchange_rates,
    how='left',
    left_on=['Order Date', 'Currency Code'],
    right_on=['Date', 'Currency'],
)

missing_exchange_rates = sales_with_rates['Exchange'].isna().sum()
print('Sales without an exchange rate:', missing_exchange_rates)

Sales without an exchange rate: 0

## 14. Check important sales rules

In [14]:
missing_delivery_dates = sales['Delivery Date'].isna().sum()
delivery_before_order = (sales['Delivery Date'] < sales['Order Date']).sum()
non_positive_quantities = (sales['Quantity'] <= 0).sum()

print('Missing delivery dates:', missing_delivery_dates)
print('Delivery dates before order dates:', delivery_before_order)
print('Zero or negative quantities:', non_positive_quantities)

Missing delivery dates: 49719
Delivery dates before order dates: 0
Zero or negative quantities: 0

## 15. Create the dataset profiling summary

This summary answers the requirements for total records, total columns, and duplicate records.

In [15]:
profiling_summary = []

for dataset_name, dataframe in datasets.items():
    profiling_summary.append({
        'Dataset': dataset_name,
        'Total Records': dataframe.shape[0],
        'Total Columns': dataframe.shape[1],
        'Duplicate Records': dataframe.duplicated().sum(),
    })

profiling_summary = pd.DataFrame(profiling_summary)
display(profiling_summary)

           Dataset  Total Records  Total Columns  Duplicate Records
0        Customers          15266             10                  0
1         Products           2517             10                  0
2            Sales          62884              9                  0
3           Stores             67              5                  0
4   Exchange Rates          11215              3                  0
5  Data Dictionary             37              3                  0

## 16. Create the column profiling table

This table shows the data type, missing values, missing percentage, and unique values for every field.

In [16]:
column_profile_rows = []

for dataset_name, dataframe in datasets.items():
    for column_name in dataframe.columns:
        missing_count = dataframe[column_name].isna().sum()
        missing_percent = (missing_count / len(dataframe)) * 100

        column_profile_rows.append({
            'Dataset': dataset_name,
            'Column': column_name,
            'Data Type': str(dataframe[column_name].dtype),
            'Missing Values': missing_count,
            'Missing Percentage': round(missing_percent, 2),
            'Unique Values': dataframe[column_name].nunique(),
        })

column_profile = pd.DataFrame(column_profile_rows)
display(column_profile)

,Dataset,Column,Data Type,Missing Values,Missing Percentage,Unique Values
0,Customers,CustomerKey,int64,0,0.00,15266
1,Customers,Gender,object,0,0.00,2
2,Customers,Name,object,0,0.00,15118
3,Customers,City,object,0,0.00,8258
4,Customers,State Code,object,0,0.00,468
5,Customers,State,object,0,0.00,512
6,Customers,Zip Code,object,0,0.00,9505
7,Customers,Country,object,0,0.00,8
8,Customers,Continent,object,0,0.00,3
9,Customers,Birthday,datetime64[ns],0,0.00,11270
10,Products,ProductKey,int64,0,0.00,2517
11,Products,Product Name,object,0,0.00,2517
12,Products,Brand,object,0,0.00,11
13,Products,Color,object,0,0.00,16
14,Products,Unit Cost USD,object,0,0.00,480
15,Products,Unit Price USD,object,0,0.00,426
16,Products,SubcategoryKey,int64,0,0.00,32
17,Products,Subcategory,object,0,0.00,32
18,Products,CategoryKey,int64,0,0.00,8
19,Products,Category,object,0,0.00,8
20,Sales,Order Number,int64,0,0.00,26326
21,Sales,Line Item,int64,0,0.00,7
22,Sales,Order Date,datetime64[ns],0,0.00,1641
23,Sales,Delivery Date,datetime64[ns],49719,79.06,1492
24,Sales,CustomerKey,int64,0,0.00,11887
25,Sales,StoreKey,int64,0,0.00,58
26,Sales,ProductKey,int64,0,0.00,2492
27,Sales,Quantity,int64,0,0.00,10
28,Sales,Currency Code,object,0,0.00,5
29,Stores,StoreKey,int64,0,0.00,67
30,Stores,Country,object,0,0.00,9
31,Stores,State,object,0,0.00,67
32,Stores,Square Meters,float64,1,1.49,36
33,Stores,Open Date,datetime64[ns],0,0.00,25
34,Exchange Rates,Date,datetime64[ns],0,0.00,2243
35,Exchange Rates,Currency,object,0,0.00,5
36,Exchange Rates,Exchange,float64,0,0.00,3473
37,Data Dictionary,Table,object,0,0.00,5
38,Data Dictionary,Field,object,0,0.00,32
39,Data Dictionary,Description,object,0,0.00,37

## 17. Display the supplied data dictionary

The data dictionary explains the meaning of each source field.

In [17]:
display(data_dictionary)

,Table,Field,Description
0,Sales,Order Number,Unique ID for each order
1,Sales,Line Item,Identifies individual products purchased as pa...
2,Sales,Order Date,Date the order was placed
3,Sales,Delivery Date,Date the order was delivered
4,Sales,CustomerKey,Unique key identifying which customer placed t...
5,Sales,StoreKey,Unique key identifying which store processed t...
6,Sales,ProductKey,Unique key identifying which product was purch...
7,Sales,Quantity,Number of items purchased
8,Sales,Currency Code,Currency used to process the order
9,Customers,CustomerKey,Primary key to identify customers
10,Customers,Gender,Customer gender
11,Customers,Name,Customer full name
12,Customers,City,Customer city
13,Customers,State Code,Customer state (abbreviated)
14,Customers,State,Customer state (full)
15,Customers,Zip Code,Customer zip code
16,Customers,Country,Customer country
17,Customers,Continent,Customer continent
18,Customers,Birthday,Customer date of birth
19,Products,ProductKey,Primary key to identify products
20,Products,Product Name,Product name
21,Products,Brand,Product brand
22,Products,Color,Product color
23,Products,Unit Cost USD,Cost to produce the product in USD
24,Products,Unit Price USD,Product list price in USD
25,Products,SubcategoryKey,Key to identify product subcategories
26,Products,Subcategory,Product subcategory name
27,Products,CategoryKey,Key to identify product categories
28,Products,Category,Product category name
29,Stores,StoreKey,Primary key to identify stores
30,Stores,Country,Store country
31,Stores,State,Store state
32,Stores,Square Meters,Store footprint in square meters
33,Stores,Open Date,Store open date
34,Exchange Rates,Date,Date
35,Exchange Rates,Currency,Currency code
36,Exchange Rates,Exchange,Exchange rate compared to USD

## 18. Answer the Phase 1 questions

A sales row is one order line. The output therefore shows both order lines and distinct orders.

In [18]:
print('PHASE 1 ANSWERS')
print('-' * 50)
print(f'Total sales records / order lines: {len(sales):,}')
print(f'Total distinct transactions / orders: {sales["Order Number"].nunique():,}')
print(f'Date range: {sales["Order Date"].min().date()} to {sales["Order Date"].max().date()}')
print()
print('Fields containing missing values:')

fields_with_missing_values = column_profile[column_profile['Missing Values'] > 0]

if fields_with_missing_values.empty:
    print('No missing values were found.')
else:
    display(fields_with_missing_values[[
        'Dataset',
        'Column',
        'Missing Values',
        'Missing Percentage',
    ]])

PHASE 1 ANSWERS
--------------------------------------------------
Total sales records / order lines: 62,884
Total distinct transactions / orders: 26,326
Date range: 2016-01-01 to 2021-02-20

Fields containing missing values:

   Dataset         Column  Missing Values  Missing Percentage
23   Sales  Delivery Date           49719               79.06
32  Stores  Square Meters               1                1.49

## Phase 1 observations

Use the displayed results to write the profiling report in your own words. Questions to confirm before cleaning:

- Does `StoreKey = 0` represent online sales?
- Do blank delivery dates represent in-store purchases?
- Should USD product prices be used as the standard reporting currency?